name: Deploy to S3

on:
  push:
    branches:
      - main
  workflow_dispatch: # Enables manual triggering of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print AWS Secrets (Masked)
        run: |
          echo "AWS Access Key ID: ${AWS_ACCESS_KEY_ID:0:4}****"
          echo "AWS Secret Access Key: ${AWS_SECRET_ACCESS_KEY:0:4}****"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.6.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          unset-current-credentials: true # Unsets any existing credentials in the runner

      - name: Sync index.html to S3
        run: |
          aws s3 cp frontend/index.html s3://chattanooga-hackathon-2024.devopschad.com/index.html
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1