name: Deploy to S3

on:
  push:
    branches:
      - main
  workflow_dispatch: # Enables manual triggering of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.6.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Sync index.html to S3
        run: |
          aws s3 cp frontend/index.html s3://chattanooga-hackathon-2024.devopschad.com/index.html
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1

      - name: Set dynamic environment variable
        run: echo "MY_VAR=some_value" >> $GITHUB_ENV

      - name: Use dynamic environment variable
        run: echo "The value of MY_VAR is $MY_VAR"
        env:
          MY_VAR: ${{ env.MY_VAR }}